/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/options': typeof OptionsRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/options': typeof OptionsRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/options': typeof OptionsRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/options' | '/settings' | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/options' | '/settings' | '/vault'
  id: '__root__' | '/' | '/options' | '/settings' | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OptionsRoute: typeof OptionsRoute
  SettingsRoute: typeof SettingsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OptionsRoute: OptionsRoute,
  SettingsRoute: SettingsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
